import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import getBlockchain from "../ethereum.js";
import axios from "axios";
import cors from "cors";

const getApi = async () => {
  const data = await axios.get(
    "https://sleepy-fortress-10819.herokuapp.com/api/1"
  );
  // const data = await axios.get("https://randomuser.me/api/");
};

export default function Home() {
  getApi();
  const [tokenInfo, setTokenInfo] = useState(undefined);
  const [images, setImages] = useState([]);

  useEffect(() => {
    const init = async () => {
      const { nft } = await getBlockchain();
      // console.log(nft.provider.provider.selectedAddress);
      const balance = await nft.balanceOf(
        nft.provider.provider.selectedAddress
      );
      console.log(`balance: ${balance}`);

      for (let i = 0; i < 2; i++) {
        let tokenURI = await nft.tokenURI(i);
        // setImages([...images, tokenURI]);
        // console.log(tokenURI);
        // console.log(img);
        setImages((images) => [...images, tokenURI]);
        // setImages((images) => [...images, tokenURI]);
      }
      // const { description } = await axios.get(images[0]);
      // console.log(img);

      // console.log(data);
      // setTokenInfo(data.result);
    };
    init();
  }, []);

  // useEffect(() => {
  //   const api = async () => {
  //     for (let i = 0; i < images.length; i++) {
  //       console.log(images[0]);
  //       // const data = await axios.get(images[0]);
  //     }
  //   };
  //   api();
  // }, [images]);

  // console.log(images);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div></div>
    </div>
  );
}

// {images.map((item, key) => {
//   return <div>{/* <image src={item}></image> */}</div>;
// })}
// export async function getServerSideProps(context) {
//   console.log(`hello: ${process.env.hello}`);
//   console.log(`hello2: ${process.env.hello2}`);

//   return {
//     props: {
//       data: [],
//     },
//   };
// }
