import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../../styles/Home.module.css";
import getBlockchain from "../ethereum.js";
import axios from "axios";
// import cors from "cors";

export default function Home() {
  const [tokenInfo, setTokenInfo] = useState(undefined);
  const [images, setImages] = useState([]);

  useEffect(() => {
    const init = async () => {
      const { nft } = await getBlockchain();
      // console.log(nft.provider.provider.selectedAddress);
      const balance = await nft.balanceOf(
        nft.provider.provider.selectedAddress
      );
      console.log(`balance: ${balance}`);

      for (let i = 0; i < 2; i++) {
        let tokenURI = await nft.tokenURI(i);

        const data = await axios.get(tokenURI);
        const picture = await data.data.properties.image.description;
        setImages((images) => [...images, picture]);
      }
    };
    init();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {images.map((item, key) => {
          return (
            <div key={key}>
              <img src={item} width="600px" alt="" />
            </div>
          );
        })}
      </div>
    </div>
  );
}

// {images.map((item, key) => {
//   return <div>{/* <image src={item}></image> */}</div>;
// })}
// export async function getServerSideProps(context) {
//   console.log(`hello: ${process.env.hello}`);
//   console.log(`hello2: ${process.env.hello2}`);

//   return {
//     props: {
//       data: [],
//     },
//   };
// }
